### ISSUE TITLE
style重复init会造成内存泄漏

### ISSUE THREAD

**Issue by qingehao** [ClimbSnail/HoloCubic_AIO#13]
我看到在进入应用时，会对应用的用到的style进行init，重复的init会造成内存泄漏的问题。
两种解决方案: 1.style 只init一次 2.调用lv_style_init之前使用lv_style_reset

**Comment by ClimbSnail** [comment]
感谢您的提议，抽空会查一下

**Comment by ClimbSnail** [comment]
> 我看到在进入应用时，会对应用的用到的style进行init，重复的init会造成内存泄漏的问题。 两种解决方案: 1.style 只init一次 2.调用lv_style_init之前使用lv_style_reset

感谢您的提议，抽空会查一下

**Comment by ClimbSnail** [comment]
已修复
