### ISSUE TITLE
Failed to write to target RAM

### ISSUE THREAD

**Issue by ormissia** [ClimbSnail/HoloCubic_AIO#26]
# MAC M1默认环境无法写入固件

> 记录一下遇到的问题，供以后遇到的人查询

Mac M1在初始搭建完PlatformIO开发环境之后，编译并写入本仓库中固件会遇到如下问题（本人使用的是`CLion`，`VSCode`应该会有相同问题）：

<img width="938" alt="QQ20220914-232550@2x" src="https://user-images.githubusercontent.com/55517494/190198324-4464f696-2d1b-4eb9-bc70-5c1a6f4a7c59.png">

在经过一顿网上冲浪之后得出如下结论（原理我就不多bb了，毕竟硬件也不会很懂🤣😂，我就直接贴解决办法了）：

> （免责声明）此方法只在本人电脑上成功解决问题，不具有普遍性。如果不能解决问题，请继续网上冲浪。

- 下载`CH343`MAC OS的驱动[下载链接](https://www.wch.cn/downloads/CH34XSER_MAC_ZIP.html)
- 安装驱动，安装时可能会被系统默认禁止，需要进入`系统偏好设置`->`安全性与隐私`->`通用`，手动允许一下。

<img width="1125" alt="QQ20220914-232821@2x" src="https://user-images.githubusercontent.com/55517494/190200862-f7b70b9f-0e26-4b55-9e6f-bb178ae6b8e8.png">

驱动安装前后串口名称对比：

- 安装前
<img width="569" alt="QQ20220914-232012@2x" src="https://user-images.githubusercontent.com/55517494/190201123-dbaaacaa-61b9-4371-9c7b-091f68a09142.png">

- 安装后
<img width="530" alt="QQ20220914-232305@2x" src="https://user-images.githubusercontent.com/55517494/190201174-5b3f9e63-b87a-45bb-9956-b0d879f8d794.png">

- 驱动安装完成之后，再次刷写固件即可成功

<img width="921" alt="QQ20220914-234521@2x" src="https://user-images.githubusercontent.com/55517494/190201364-e547442c-a721-4526-abf6-3bc0942c641f.png">

**Comment by ormissia** [comment]
我先把issue开着吧，烦请@ClimbSnail看下是否需要处理

**Comment by ClimbSnail** [comment]
可能需要过段时间，有复现条件了再看了。目前没在mac上测试过这些

**Comment by YuhangQ** [comment]
感谢老哥，m1 实测有用，我使用的是 vscode PlatformIO 环境
