### ISSUE TITLE
Picture.cpp代码无效问题

### ISSUE THREAD

**Issue by huasyuan** [ClimbSnail/HoloCubic_AIO#32]
具体在第39行
36if (size == 0)
37    {
38        // 默认值
39        cfg->switchInterval = 0; // 是否自动播放下一个（0不切换 默认10000毫秒）
40        write_config(cfg);
41    }
当switchInterval = 0;为0是它还是会自动播放下一个
而且在网页配置为0 也是一样的

**Comment by ClimbSnail** [comment]
已修复
